### ISSUE TITLE
Getting the error ```Error: Timeout reached```

### ISSUE THREAD

**Issue by Yassas11** [KK-Designs/UpdateHub#7] opened 2023-07-24 05:58 UTC
Getting the error ```Error: Timeout reached
    at C:\Users\yassa\AppData\Local\Programs\update-hub\resources\app.asar\preload.js:1:815325```.

**Comment by KK-Designs** [comment] 2023-07-24 07:14
This error has to do with the system language setting. Please temporarily change it to English while we work on a fix.

**Comment by KK-Designs** [comment] 2023-07-24 07:16
Closing as it is a duplicate of #6

**Closed by KK-Designs** 2023-07-24 07:16 UTC
Labels: bug, duplicate, applications

**Comment by KK-Designs** [comment] 2023-07-24 07:18
Changing issue closing status to duplicate

**Comment by KK-Designs** [comment] 2023-09-12 04:17
Fixed in v2.1.0
